<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="asp" %>
<%@ Register tagprefix="mike" TagName="access_rule_summary" Src="~/Goodday/OnlyAdmin/Access/access_rule_summary.ascx" %>
<%@ Register tagprefix="mike" TagName="access_rules" Src="~/Goodday/OnlyAdmin/Access/access_rules.ascx" %>
<%@ Register tagprefix="mike" TagName="active_users" Src="~/Goodday/OnlyAdmin/Access/active_users.ascx" %>
<%@ Register tagprefix="mike" TagName="add_user" Src="~/Goodday/OnlyAdmin/Access/add_user.ascx" %>
<%@ Register tagprefix="mike" TagName="alphalinks" Src="~/Goodday/OnlyAdmin/Access/alphalinks.ascx" %>
<%@ Register tagprefix="mike" TagName="edit_user" Src="~/Goodday/OnlyAdmin/Access/edit_user.ascx" %>
<%@ Register tagprefix="mike" TagName="locked_users" Src="~/Goodday/OnlyAdmin/Access/locked_users.ascx" %>
<%@ Register tagprefix="mike" TagName="online_users" Src="~/Goodday/OnlyAdmin/Access/online_users.ascx" %>
<%@ Register tagprefix="mike" TagName="roles" Src="~/Goodday/OnlyAdmin/Access/roles.ascx" %>
<%@ Register tagprefix="mike" TagName="users" Src="~/Goodday/OnlyAdmin/Access/users.ascx" %>
<%@ Register tagprefix="mike" TagName="users_by_role" Src="~/Goodday/OnlyAdmin/Access/users_by_role.ascx" %>
